### ISSUE TITLE
Portal transports to spawn in original world

### ISSUE THREAD

**Issue by fischerlord** [OGBlackDiamond/Proxy-Portals#1]
Hello! I have noticed the portal plugin doesn't seem to transport me to another server- it just sends me to spawn in my "Lobby" world.  

Version of server is Paper 1.21.1. I did notice in your code it's exporting to the BungeeCord plugin, does that mean I need to run Velocity in BungeeCord mode and not Modern? 

Thanks

**Comment by OGBlackDiamond** [comment]
Hey there, thanks for your comment.

Usually this happens when there isnt a server to transport you to. I would make sure that you registered the portal with the exact name as it is in your `velocity.toml`. I would also check to see if youre getting any errors in your velocity console. You do not need to use bungeecord, ita just sending messages to an internal channel called BungeeCord, you can find API information for that [here](https://docs.papermc.io/paper/dev/plugin-messaging).

Also, if you need to change the name registered to a portal, dont forget to deregister the server beforehand.

**Comment by fischerlord** [comment]
I checked and I am using the correct server names. I'm able to switch with the /server command. Unfortunately there is nothing in the velocity console. Do you have a log this is writing to? Another thing to note is I don't think it's checking whether or not a server is registered when I deregister it- the command says it works everytime, even if I enter a random string. If I get the chance I'll write something up and submit a pull request. Cheers!

**Comment by OGBlackDiamond** [comment]
Huh, thats odd. I don't have a log. The success message is basically just telling you that it didn't throw an error lol, so its not super advanced. I'm 100% open to PRs if you can figure out whats wrong, everything works fine on my network using modern player forwarding.

**Comment by OGBlackDiamond** [comment]
Looking back at my old code, the only thing that I can think of being wrong is that the database returns a wrong or null value. I don't know the exact name of the server you're trying to link with but I would remove any special characters and just use a string of characters, no spaces or anything like that. Other than that, I have no idea what the issue could be. If you find anything, feel free to open a PR or let me know.

**Comment by fischerlord** [comment]
Check out the PR I sent- I feel like a dork not enabling plugin messaging from the getgo. (To be fair, I haven't touched Java in like 5 years, and never made a Minecraft plugin). I work in web dev and IT so this is pretty new to me.
